In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelBinarizer

In [4]:
Data = pd.read_csv('/kaggle/input/car-price-prediction/CarPrice_Assignment.csv')
Data.head(20)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
13,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105.000
14,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
17,18,0,bmw x3,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880.000
18,19,2,chevrolet impala,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151.000
19,20,1,chevrolet monte carlo,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295.000

In [5]:
Data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [6]:
Data.describe(include = "all")

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205,205,205,205,205,205,205,205.000000,...,205.000000,205,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
unique,NaN,NaN,147,2,2,2,5,3,2,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,toyota corona,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,6,185,168,115,96,120,202,NaN,...,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,103.000000,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,...,126.907317,NaN,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,...,41.642693,NaN,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,97.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [7]:
#Look if your data is skewed(Usin the IQR = Q3 - Q1 to  see where the data is more skewed to if it s)
#Look for relationships between the features and the targets
#Look for more Normal distribution
#Look for Outliers using BoxPlots or by calculating the lower and the upper bound(Lower Bound : Q1 -  1.5IQ / Upper Bound : Q3 - 1.5)
#Look if the data needs scaling or not

In [8]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [9]:
Data_R = Data.copy()
Data_R

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [10]:
Data_R['doornumber'] = Data_R['doornumber'].replace({'two' : 2 , 'four' : 4})
Data_R['doornumber'] = Data_R['doornumber'].astype(int)
Data_R.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    int64
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(9), object(9)
memory usage: 41.8+ KB

/tmp/ipykernel_30/1603227038.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Data_R['doornumber'] = Data_R['doornumber'].replace({'two' : 2 , 'four' : 4})

In [11]:
Data_R

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,4,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,4,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,4,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,4,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [12]:
#Before transforming the catiegorical valuces to numerical values check for outliers 
#Look for unique values and try to minimize them by using Target encoding or Other method 
#The problem here if i want to mnimize the data using Target is that i will lose some other related features to each category i use target encoding on

In [13]:
Data_R.describe(include = 'all')

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205,205,205,205.000000,205,205,205,205.000000,...,205.000000,205,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
unique,NaN,NaN,147,2,2,NaN,5,3,2,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,toyota corona,gas,std,NaN,sedan,fwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,6,185,168,NaN,96,120,202,NaN,...,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,103.000000,0.834146,NaN,NaN,NaN,3.121951,NaN,NaN,NaN,98.756585,...,126.907317,NaN,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,NaN,NaN,NaN,0.994966,NaN,NaN,NaN,6.021776,...,41.642693,NaN,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,86.600000,...,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,94.500000,...,97.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,97.000000,...,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,102.400000,...,141.000000,NaN,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,120.900000,...,326.000000,NaN,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [14]:
Data_R['price'].nunique()
#The problem here is that i would want to use target encoding for each feature of the data that has  non unique prices 
#But i can t really do that here as there s the risk of overfitting for this training data as there s many features for each car

189

In [15]:
Data_R['CarName'].nunique()
#There s so manmy non unique car names so i will be dropping so many layers as they are just going to cause overfitting
#I will also drop the car ID because it s nothing but the index + 1

147

In [36]:
Data_R

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,4,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,4,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,4,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,4,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [35]:
Data_R_NoD = Data_R.drop_duplicates(subset = "CarName",keep = "first")
Data_R_NoD
#even thought this helped with some data still there s a problem i don t quite understand 
#for example look at the car with id 4 and the car with id 5 you will notice that they are the same car 
#but still even thought they are the same car some things are not similar like the wheelbase...

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,4,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,4,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,197,-2,volvo 244dl,gas,std,4,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985.0
197,198,-1,volvo 245,gas,std,4,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515.0
198,199,-2,volvo 264gl,gas,turbo,4,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420.0
199,200,-1,volvo diesel,gas,turbo,4,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950.0
203,204,-1,volvo 246,diesel,turbo,4,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0

In [18]:
Data_R_NoD.describe(include = "all")

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,147.000000,147.000000,147,147,147,147.000000,147,147,147,147.000000,...,147.000000,147,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
unique,NaN,NaN,147,2,2,NaN,5,3,2,NaN,...,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,alfa-romero giulia,gas,std,NaN,sedan,fwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1,132,122,NaN,68,88,144,NaN,...,NaN,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,96.530612,0.931973,NaN,NaN,NaN,3.020408,NaN,NaN,NaN,98.087755,...,126.523810,NaN,3.303469,3.266599,10.255238,102.734694,5157.823129,25.537415,31.047619,13248.402497
std,60.034386,1.225639,NaN,NaN,NaN,1.003210,NaN,NaN,NaN,6.108257,...,46.137575,NaN,0.272921,0.282661,4.051558,39.467227,476.132417,6.928472,7.326377,8694.473053
min,1.000000,-2.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,86.600000,...,61.000000,NaN,2.680000,2.360000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,44.500000,0.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,94.500000,...,97.000000,NaN,3.050000,3.135000,8.600000,69.000000,4800.000000,19.500000,25.000000,7429.000000
50%,94.000000,1.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,96.500000,...,110.000000,NaN,3.270000,3.270000,9.000000,95.000000,5200.000000,25.000000,30.000000,9895.000000
75%,146.500000,2.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,100.400000,...,143.000000,NaN,3.580000,3.400000,9.400000,116.000000,5500.000000,31.000000,37.000000,16207.500000
max,204.000000,3.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,120.900000,...,326.000000,NaN,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [19]:
Data_R_NoD.median(numeric_only = "True")

car_ID                94.00
symboling              1.00
doornumber             4.00
wheelbase             96.50
carlength            171.70
carwidth              65.40
carheight             53.70
curbweight          2380.00
enginesize           110.00
boreratio              3.27
stroke                 3.27
compressionratio       9.00
horsepower            95.00
peakrpm             5200.00
citympg               25.00
highwaympg            30.00
price               9895.00
dtype: float64

In [41]:
Data_R_NoD.mode()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,1.0,Nissan versa,gas,std,4.0,sedan,fwd,front,94.5,...,92.0,mpfi,3.62,3.4,9.0,68.0,5500.0,31.0,38.0,5572.0
1,2,NaN,alfa-romero Quadrifoglio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6692.0
2,3,NaN,alfa-romero giulia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7295.0
3,4,NaN,alfa-romero stelvio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7609.0
4,5,NaN,audi 100 ls,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7775.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,197,NaN,volvo 246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,198,NaN,volvo 264gl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,199,NaN,volvo diesel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,200,NaN,vw dasher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,204,NaN,vw rabbit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Look for the central tendency of each feature
#Before doing that we need to check for the linearity relation between each feature and the target and we need to look for outliers

In [22]:
Data_R_NoD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 0 to 203
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            147 non-null    int64
 1   symboling         147 non-null    int64
 2   CarName           147 non-null    object
 3   fueltype          147 non-null    object
 4   aspiration        147 non-null    object
 5   doornumber        147 non-null    int64
 6   carbody           147 non-null    object
 7   drivewheel        147 non-null    object
 8   enginelocation    147 non-null    object
 9   wheelbase         147 non-null    float64
 10  carlength         147 non-null    float64
 11  carwidth          147 non-null    float64
 12  carheight         147 non-null    float64
 13  curbweight        147 non-null    int64
 14  enginetype        147 non-null    object
 15  cylindernumber    147 non-null    object
 16  enginesize        147 non-null    int64
 17  fuelsystem        147 non-null    object
 18  boreratio         147 non-null    float64
 19  stroke            147 non-null    float64
 20  compressionratio  147 non-null    float64
 21  horsepower        147 non-null    int64
 22  peakrpm           147 non-null    int64
 23  citympg           147 non-null    int64
 24  highwaympg        147 non-null    int64
 25  price             147 non-null    float64
dtypes: float64(8), int64(9), object(9)
memory usage: 31.0+ KB

In [23]:
Data_Num = Data_R_NoD.select_dtypes(include = np.number)
Q1 =  Data_Num.quantile(0.25)
Q3 =  Data_Num.quantile(0.70)
IQR = Q3 - Q1
Upper_Bound = Q3 + 1.5*IQR
Lower_Bound = Q1 - 1.5*IQR
outliers = ((Data_Num < Lower_Bound)|(Data_Num  > Upper_Bound))
outliers.sum()

car_ID               0
symboling            0
doornumber           0
wheelbase           17
carlength           11
carwidth             8
carheight            0
curbweight           4
enginesize           9
boreratio            0
stroke              16
compressionratio    19
horsepower           9
peakrpm              2
citympg              2
highwaympg           3
price               18
dtype: int64

In [24]:
#Now after i found how many outliers there s in each feature i need to find those outliers and their rows and their values to see if they can be considered outliers or not as this dataset is about cars so it makes sense to find some really expensive cars and really cheap cars and i don t want to loose data

In [25]:
Outliers_R = Data_R_NoD[outliers.any(axis = 1)]
Outliers_R.shape

(53, 26)

In [26]:
Outliers_R.describe()

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,98.226415,0.867925,3.094340,100.462264,178.769811,67.018868,53.783019,2851.811321,152.433962,3.436038,3.256226,12.462264,118.754717,4949.056604,24.188679,29.075472,18726.908811
std,59.017156,1.316139,1.005067,8.687330,15.180182,2.750668,2.632543,648.029263,60.637482,0.264839,0.423648,6.146082,49.830831,569.285193,8.573341,9.300226,11540.403843
min,1.000000,-1.000000,2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.910000,2.360000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,49.000000,0.000000,2.000000,94.500000,168.900000,65.000000,52.000000,2319.000000,108.000000,3.240000,2.900000,8.300000,82.000000,4500.000000,17.000000,24.000000,9298.000000
50%,109.000000,0.000000,4.000000,97.300000,175.600000,66.500000,53.700000,2800.000000,132.000000,3.540000,3.350000,9.000000,111.000000,4800.000000,22.000000,25.000000,13495.000000
75%,144.000000,2.000000,4.000000,107.900000,190.900000,68.900000,55.700000,3252.000000,183.000000,3.620000,3.470000,21.000000,155.000000,5200.000000,28.000000,33.000000,28248.000000
max,204.000000,3.000000,4.000000,120.900000,208.100000,72.000000,58.700000,4066.000000,326.000000,3.800000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [27]:
#Here i have 53 outliers bu i must check them all to mmake sure what are the outliers and what are not and are just cars that are really expensive or cars that are really cheap (for example the Target price)

In [28]:
Outliers_R.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
7,8,1,audi 5000,gas,std,4,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,4,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,2,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167

In [29]:
Outliers_R.median(numeric_only = "True")

car_ID                109.00
symboling               0.00
doornumber              4.00
wheelbase              97.30
carlength             175.60
carwidth               66.50
carheight              53.70
curbweight           2800.00
enginesize            132.00
boreratio               3.54
stroke                  3.35
compressionratio        9.00
horsepower            111.00
peakrpm              4800.00
citympg                22.00
highwaympg             25.00
price               13495.00
dtype: float64

In [30]:
Outliers_R.mode().iloc[0]

car_ID                               1
symboling                          0.0
CarName             alfa-romero giulia
fueltype                           gas
aspiration                         std
doornumber                         4.0
carbody                          sedan
drivewheel                         rwd
enginelocation                   front
wheelbase                         97.0
carlength                        172.0
carwidth                          65.4
carheight                         55.7
curbweight                      2548.0
enginetype                         ohc
cylindernumber                    four
enginesize                       108.0
fuelsystem                        mpfi
boreratio                         3.62
stroke                             3.4
compressionratio                   9.0
horsepower                       123.0
peakrpm                         4800.0
citympg                           16.0
highwaympg                        25.0
price                           7775.0
Name: 0, dtype: object

In [31]:
#To check all the outliar features of each car from those 53 cars i need either to plot them or use some external knowledge and compare each feature for each car to find the outlier

In [32]:
lb = LabelBinarizer()
encoded_Columns = lb.fit_transform(Data[['CarName','fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem']])

ValueError: Multioutput target data is not supported with label binarization